name: Unity CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  tests:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-test-runner@v3
        with:
          projectPath: unity_client
          unityVersion: 2022.3.17f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: All
          testFilters: "PerformanceTests"
          artifactsPath: TestResults
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
